"""fix_jobstatus_string_enum

Revision ID: e351247e703b
Revises: 46780f92d352
Create Date: 2026-08-05 15:11:24.028556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy.dialects.postgresql as postgresql


# revision identifiers, used by Alembic.
revision: str = 'e351247e703b'
down_revision: Union[str, Sequence[str], None] = '46780f92d352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Ensure the postgres enum type exists
    jobstatus_enum = postgresql.ENUM(
        'QUEUED', 'PLANNING', 'RESEARCHING', 'VERIFYING', 
        'REPORTING', 'COMPLETED', 'FAILED', 
        name='jobstatus', 
        create_type=False
    )
    jobstatus_enum.create(op.get_bind(), checkfirst=True)

    # 2. Explicit ALTER COLUMN with USING clause to safely cast/realign existing rows
    op.execute(
        "ALTER TABLE jobs ALTER COLUMN status TYPE jobstatus USING status::text::jobstatus"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
